// Package crm Code generated by swaggo/swag. DO NOT EDIT
package crm

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/book": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户创建图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "创建图书",
                "parameters": [
                    {
                        "description": "EBook payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Author": {
            "type": "object",
            "properties": {
                "UpdatedAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "authorName": {
                    "type": "string"
                },
                "createdAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Book": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/models.Author"
                },
                "authorId": {
                    "type": "integer"
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Category"
                    }
                },
                "coverUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isbn": {
                    "type": "string"
                },
                "price": {
                    "description": "价格,单位分",
                    "type": "integer"
                },
                "pubdate": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "publisher": {
                    "$ref": "#/definitions/models.Publisher"
                },
                "publisherId": {
                    "type": "integer"
                },
                "sourceUrl": {
                    "type": "string"
                },
                "status": {
                    "description": "0-下架,1-上架",
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "1-电子书,2-实体,3-电子书+实体",
                    "type": "integer"
                },
                "updatedAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                },
                "createdAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                },
                "updatedAt": {
                    "$ref": "#/definitions/types.GxTime"
                }
            }
        },
        "models.Publisher": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "$ref": "#/definitions/types.GxTime"
                },
                "id": {
                    "type": "integer"
                },
                "publisherName": {
                    "type": "string"
                },
                "updatedAt": {
                    "$ref": "#/definitions/types.GxTime"
                }
            }
        },
        "types.GxTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
